routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/','IndexController');
Route::get('/dashboard','IndexController@index');
Route::get('/distribusi','HomeController@distribusi');
Route::get('/datadonasi/distribusi/{id}','DatadonasiController@jemputan');
Route::put('/datadonasi/distribusi/{id?}','DatadonasiController@update1');
Route::resource('/penjemputan','PenjemputanController');
Route::resource('/datadonatur', 'DatadonaturController');


Route::get('/register/petugas',function(){
    return view('auth.registerAdmin');
});

Route::get('/rekap/{id}','HomeController@rekap');
Route::get('datadonasi/donasi/{id}','DatadonasiController@create');
Route::get('datadonasi/distribusi','DatadonasiController@distribusi');
Route::get('databencana/post/{kode_bencana}', 'DatabencanaController@postingan');


Route::group(['middleware'=> 'App\Http\Middleware\MemberMiddleware'],
    function ()
    {
        Route::resource('datadonasi', 'DatadonasiController');
        Route::match(['get','post'],'/memberOnlyPage/',
            'HomeController@member' );
    });

Route::group(['middleware'=> 'App\Http\Middleware\AdminMiddleware'],
    function ()
    {
        Route::resource('datapetugas', 'DatapetugasController');
        Route::match(['get','post'],'/adminOnlyPage/',
            'HomeController@admin' );
    });

Route::group(['middleware'=> 'App\Http\Middleware\PetugasMiddleware'],
    function ()
    {
        Route::resource('databencana', 'DatabencanaController');
        Route::resource('datapetugas', 'DatapetugasController');
        Route::resource('datadonasi', 'DatadonasiController');
        Route::resource('datadonatur', 'DatadonaturController');
        Route::match(['get','post'],'/petugasOnlyPage/',
            'HomeController@petugas' );
    });
// Route::get('/donasi',function(){
//     return view('datadonasi/index');
// });

//
//Route::get('databencana', 'DatabencanaController@index');
//Route::post('databencana', 'DatabencanaController@upload');
//Route::delete('databencana/{id}', 'DatabencanaController@destroy');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Datadonasi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Datadonasi extends Model
{
    protected $table = 'datadonasis';
    protected $fillable = ['user_id','databencana_id', 'jenis_barang', 'donasi', 'jumlah', 'keterangan', 'lokasi'];

    public function donasis(){
        return $this->belongsTo('App\Penjemputan','datadonasi_id','id');
    }
}

app/Http/Controllers/DatadonasiController.php
<?php

namespace App\Http\Controllers;

use App\Penjemputan;
use Illuminate\Http\Request;
use App\Databencana;
use App\Datadonasi;
use App\User;
use Illuminate\Http\Response;

class DatadonasiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

//    public function petugas(Request $request){
//        return view('middleware')->withMessage("Petugas");
//    }


    public function jemputan($id){
        $penjemputan = Penjemputan::find($id);
        return view('datadonasi.editpenjemputan',compact(['penjemputan']));
    }

    public function index()
    {
        $datadonasi = User::select("users.*","datadonasis.*")
        ->join("datadonasis", "users.id", "=", "datadonasis.user_id")
//        ->where("penjemputan.user_id", $id)
        ->get();
//        dd($datadonasi);
//        $datadonasi = Datadonasi::all()->toArray();
        return view('datadonasi.index', compact('datadonasi'));
    }
//    public function berhasil(){
//        return view('datadonasi.berhasil')->with('success', 'Data ditambahkan');
//    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        $databencana = Databencana::find($id);
        return view('datadonasi.create', compact('databencana'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $databencana = Databencana::get();
        $this->validate($request, [
            'user_id'   =>  'required',
            'databencana_id'    =>  'required',
            'jenis_barang'     =>  'required',
			'donasi'           =>  'required',
			'jumlah'           =>  'required',
			'keterangan'       =>  'required',
			'lokasi'           =>  'required'
        ]);
       $input['user_id']        =   $request->user_id;
       $input['databencana_id'] =   $request->databencana_id;
       $input['jenis_barang']   =   $request->jenis_barang;
       $input['donasi']         =   $request->donasi;
       $input['jumlah']         =   $request->jumlah;
       $input['keterangan']     =   $request->keterangan;
       $input['lokasi']         =   $request->lokasi;
       Datadonasi::create($input);
        return new Response(view('welcome',compact('databencana')));
//        $datadonasi = new Datadonasi([
//            'kode_donasi'      =>  $request->get('kode_donasi'),
//            'jenis_barang'     =>  $request->get('jenis_barang'),
//			'donasi'           =>  $request->get('donasi'),
//			'jumlah'           =>  $request->get('jumlah'),
//			'keterangan'       =>  $request->get('keterangan'),
//			'lokasi'           =>  $request->get('lokasi')
//        ]);
//        $datadonasi->save();
//        return redirect()->route('')->with('success','Donasi berhasil ditambahkan');
        //return view('welcome')->with('success','Donasi berhasil ditambahkan')
//        return redirect()->route('datadonasi.berhasil   ')->with('success', 'Data Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $datadonasi = Datadonasi::find($id);
//        $datadonasi = User::select("users.*","datadonasis.*")->join("datadonasis", "users.id", "=", "datadonasis.user_id")->where("datadonasis.id", $id)->get();

//        dd($datadonasi);
        return view('datadonasi.edit', compact(['datadonasi','id']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
//            'user_id'      =>  'required',
//            'databencana_id'=>'required',
            'jenis_barang' => 'required',
            'donasi' => 'required',
            'jumlah' => 'required',
            'keterangan' => 'required',
            'lokasi' => 'required'
        ]);
        $datadonasi = Datadonasi::find($id);
        $datadonasi->id = $request->get('kode_donasi');
//        $datadonasi->user_id = $request->get('user_id');
//        $datadonasi->databencana_id = $request->get('databencana_id');
        $datadonasi->jenis_barang = $request->get('jenis_barang');
        $datadonasi->donasi = $request->get('donasi');
        $datadonasi->jumlah = $request->get('jumlah');
        $datadonasi->keterangan = $request->get('keterangan');
        $datadonasi->lokasi = $request->get('lokasi');
        $datadonasi->save();


        $input['datadonasi_id'] =   $request->kode_donasi;
        $input['user_id']        =   $datadonasi->user_id;
        $input['status']        = $request->status;
        $input['tanggal']       = $request->tanggal;
        Penjemputan::create($input);

        $datadonasi = User::select("users.*","datadonasis.*")
            ->join("datadonasis", "users.id", "=", "datadonasis.user_id")
//        ->where("penjemputan.user_id", $id)
            ->get();
        return new Response(view('datadonasi.index',compact('datadonasi')));
    }

    public function update1(Request $request, $id)
    {

        $penjemputan = Penjemputan::find($id);
        $input['datadonasi_id'] =   $penjemputan->datadonasi_id;
        $input['user_id']        =   $penjemputan->user_id;
        $input['status']        = $request->status;
        $input['tanggal']       = $request->tanggal;
        Penjemputan::create($input);

        $datadonasi = User::select("users.*","datadonasis.*")
            ->join("datadonasis", "users.id", "=", "datadonasis.user_id")
//        ->where("penjemputan.user_id", $id)
            ->get();
        return new Response(view('datadonasi.index',compact('datadonasi')));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $datadonasi = Datadonasi::find($id);
        $datadonasi->delete();
        return redirect()->route('datadonasi.index')->with('success', 'Data Deleted');
    }


    public function distribusi(){
//        $datadonasi = Penjemputan::get()
//            ->where("penjemputan.datadonasis_id","datadonasis.id")
//            ->get();
        $datadonasi = Datadonasi::select("datadonasis.*","penjemputan.*")
            ->join("penjemputan", "penjemputan.datadonasi_id", "=", "datadonasis.id")
            ->get();
        //            ->where("penjemputan.datadonasi_id", "datadonasis.id")
//            dd($userAddresses);
        return view('datadonasi.distribusi',compact(['datadonasi']));
    }
}

resources/views/datadonasi/berhasil.blade.php
@extends('master')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        Donasi Berhasil ditambahkan
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/datadonasi/create.blade.php
@extends('master')
@section('title')
 <title>Formulir Donasi</title>
 @endsection

@section('content')
 <script src="https://code.jquery.com/jquery-3.2.1.js"></script>

 <div class="about-area area-padding">
 <div class="container">
 <div class="row">
  @guest
   <br/>
  <br/>
  <div  class="text-center">
   <h3> Anda Belum Login Silahkan Login terlebih dahulu</h3>
   <a href="{{url('/login')}}" class="btn btn-warning">LOGIN</a>
  </div>
   @else
   <br />
   <div class="text-center">
   <h1>Tambah Bantuan Donasi</h1>
  </div>
  <hr>
   <br />
   @if(count($errors) > 0)
    <div class="alert alert-danger">
     <ul>
      @foreach($errors->all() as $error)
       <li>{{$error}}</li>
      @endforeach
     </ul>
    </div>
   @endif
   @if(\Session::has('success'))
    <div class="alert alert-success">
     <p>{{ \Session::get('success') }}</p>
    </div>
   @endif


    <form method="post" action="{{url('datadonasi')}}">
     {{csrf_field()}}
     <div class="table table-bordered table-hover" id="tab_logic">

      <div class="container">
       <div class="row clearfix">
        <div class="col-md-12 column">
         <table class="table table-bordered table-hover" id="tab_logic">
          <thead>
          <tr >
           <th class="text-center">
            #
           </th>
           <th class="text-center">
            Kode Donatur
           </th>
           <th class="text-center">
            Kode Bencana
           </th>
           <th class="text-center">
            Jenis Barang
           </th>
           <th class="text-center">
            Donasi
           </th>
           <th class="text-center">
            Jumlah
           </th>
           <th class="text-center">
            Keterangan
           </th>
          </tr>
          </thead>
          <tbody>
          <tr id='addr0'>
           <td>
            1
           </td>
           <td>
            <input type="text" name="user_id" class="form-control" value="{{Auth::user()->id}}" placeholder="{{Auth::user()->id}}" />
           </td>
           <td>
            <input type="text" name="databencana_id" class="form-control" value="{{$databencana->id}}" placeholder="{{$databencana->id}}" />
           </td>
           <td>
            <select class="form-control" name="jenis_barang">
             <option value="Sandang">Sandang</option>
             <option value="Pangan">Pangan</option>
             <option value="Papan">Papan</option>
            </select>
           </td>
           <td>
            <input type="text" name='donasi' placeholder='Donasi' class="form-control"/>
           </td>
           <td>
            <input type="text" name='jumlah' placeholder='jumlah' class="form-control"/>
           </td>
           <td>
            <input type="text" name='keterangan' placeholder='keterangan' class="form-control"/>
           </td>
          </tr>
          <tr id='addr1'></tr>
          </tbody>
         </table>
        </div>
       </div>
       {{--<a href="#" id="add_row" class="btn btn-primary pull-right">Tambahkan</a>--}}
       {{--<button id="add_row" class="btn btn-primary pull-right" >Tambahkan</button>--}}
      </div>
      <div class="form-group">
       <b><p>Lokasi Bencana</p></b>
       <input type="text" name="lokasi" value="{{$databencana->lokasi_bencana}}" placeholder="{{$databencana->lokasi_bencana}}" >
      </div>
      <div class="form-group">
       <input type="submit" class="btn btn-primary" />
      </div>
     </div>
    </form>
    @endguest


  </div>
 </div>





 </div>

<script>
    $(document).ready(function(){
        var i=1;
        $("#add_row").click(function(){
            $('#addr'+(i-1)).find('input').attr('disabled',true);
            $('#addr'+i).html("<td>"+ (i+1) +"</td><td><input type='text' name='kode_donasi"+i+"'  placeholder='{{$databencana->id}}' class='form-control input-md' disabled/></td> <td><select class='form-control' name='jenis_barang"+i+"'><option>Sandang</option><option>Pangan</option><option>Papan</option> </td><td><input type='text' name='donasi"+i+"' placeholder='donasi' class='form-control input-md'/></td><td><input type='text' name='jumlah"+i+"' placeholder='jumlah' class='form-control input-md'/></td><td><input type='text' name='keterangan"+i+"' placeholder='keterangan' class='form-control input-md'/></td>");

            $('#tab_logic').append('<tr id="addr'+(i+1)+'"></tr>');
            i++;
        });
    });

</script>

@endsection

resources/views/datadonasi/distribusi.blade.php
@extends('layouts\app1')
@section('title')
    <title>Donate | Data Donasi</title>
@endsection

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Donasi
                <small>Rekap Data Donasi</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Dahsboard</a></li>
                <li><a href="#"><i class="fa fa-database"></i>Donasi </a></li>
                <li class="active">Data Donasi</li>
            </ol>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">Tabel Rekap Data Donasi</h3>
                        </div>
                        @if(count($errors) > 0)

                            <div class="alert alert-danger">
                                <ul>
                                    @foreach($errors->all() as $error)
                                        <li>{{$error}}</li>
                                    @endforeach
                                </ul>
                            </div>
                    @endif
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Donasi</th>
                                    <th>Lokasi</th>
                                    <th>Tanggal</th>
                                    <th>Status</th>
                                    <th>Opsi</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                $number = 1;
                                ?>
                                @foreach($datadonasi as $row)
                                    <tr>
                                        <td>{{$number}}</td>
                                        <td>{{$row->jenis_barang}}</td>
                                        <td>{{$row->lokasi}}</td>
                                        <td>{{$row->tanggal}}</td>
                                        <td>
                                            @if($row->status=='0')
                                                <a href="#" class="btn btn-danger">Belum Dijemput</a>
                                            @endif
                                            @if($row->status=='1')
                                                <a href="#" class="btn btn-warning">Sedang Dijemput</a>
                                            @endif
                                            @if($row->status=='2')
                                                <a href="#" class="btn btn-primary">Sudah Dijemput</a>
                                            @endif
                                            @if($row->status=='3')
                                                <a href="#" class="btn btn-success">Sudah Terdistribusi</a>
                                            @endif
                                        </td>
                                        <td>
                                            <a href="{{action('DatadonasiController@jemputan', $row['id'])}}" class="btn btn-info">Ubah</a>
                                        </td>
                                    </tr>

                                    <?php
                                    $number++;
                                    ?>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
    </div>
@endsection

resources/views/datadonasi/edit.blade.php
<?php $number=1; ?>
@extends('layouts.app1')
@section('title')
 <title>Donate|Data Donasi</title>
@endsection


@section('content')

 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
   <h1>
    Donasi
    <small>Penjemputan Data Donasi</small>
   </h1>
   <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Dahsboard</a></li>
    <li><a href="#"><i class="fa fa-database"></i>Donasi </a></li>
    <li class="active">Data Donasi</li>
   </ol>
  </section>

  <section class="content-header">
   <div class="row">
    <div class="col-md-12">
     <br />
     <h3>Edit Data</h3>
     <br />
     @if(count($errors) > 0)
      <div class="alert alert-danger">
       <ul>
        @foreach($errors->all() as $error)
         <li>{{$error}}</li>
        @endforeach
       </ul>
       @endif
      </div>
      <form method="post" action="{{action('DatadonasiController@update', $datadonasi->id)}}" enctype="multipart/form-data">
       {{csrf_field()}}
       <input type="hidden" name="_method" value="PATCH" />
       <div class="form-group">
        <label for="type" class="col-md-4 col-form-label text-md-right">{{__('Kode Donasi')}}</label>
        <input type="text" name="kode_donasi" class="form-control" value="{{$datadonasi->id}}" placeholder="Masukkan Kode Donasi" />
       </div>
       <div class="form-group">
         <label for="type" class="col-md-4 col-form-label text-md-right">{{__('Jenis Barang')}}</label>
         <input type="text" name="jenis_barang" class="form-control" value="{{$datadonasi->jenis_barang}}" placeholder="Masukkan Jenis Barang" />
        </div>
        <div class="form-group">
         <label for="type" class="col-md-4 col-form-label text-md-right">{{__('Donasi')}}</label>
         <input type="text" name="donasi" class="form-control" value="{{$datadonasi->donasi}}" placeholder="Masukkan Donasi" />
        </div>
        <div class="form-group">
         <label for="type" class="col-md-4 col-form-label text-md-right">{{__('Jumlah')}}</label>
         <input type="text" name="jumlah" class="form-control" value="{{$datadonasi->jumlah}}" placeholder="Masukkan Jumlah Donasi" />
        </div>
        <div class="form-group">
         <label for="type" class="col-md-4 col-form-label text-md-right">{{__('Keterangan')}}</label>
         <input type="text" name="keterangan" class="form-control" value="{{$datadonasi->keterangan}}" placeholder="Masukkan Keterangan" />
        </div>
        <div class="form-group">
         <label for="type" class="col-md-4 col-form-label text-md-right">{{__('Lokasi')}}</label>
         <input type="text" name="lokasi" class="form-control" value="{{$datadonasi->lokasi}}" placeholder="Masukkan Lokasi" />
        </div>
        <div class="form-group row">
         <label for="type" class="col-md-4 col-form-label text-md-right">{{__('Status Donasi')}}</label>
         <div class="col-md-6">
          <select class="form-control" name="status" id="status">
           <option value="0">Belum dijemput</option>
           <option value="1">Sedang dijemput</option>
           <option value="2">Sudah dijemput</option>
           <option value="3">Terdistribusi</option>
          </select>
         </div>
        </div>
        <div class="form-group">
         <label for="type" class="col-md-4 col-form-label text-md-right">{{__('Tanggal Penjemputan')}}</label>
         <input type="date" name="tanggal" class="form-control"  placeholder="Masukkan Tanggal" />
        </div>

        <div class="form-group">
         <input type="submit" class="btn btn-primary" value="Edit" />
        </div>
       </form>
      </div>
    </div>
  </section>
   </div>
@endsection

resources/views/datadonasi/index.blade.php
<?php $number=1; ?>
@extends('layouts.app1')
@section('title')
    <title>Donate|Data Donasi</title>
@endsection


@section('content')

 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
   <h1>
    Donasi
    <small>Rekap Data Donasi</small>
   </h1>
   <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Dahsboard</a></li>
    <li><a href="#"><i class="fa fa-database"></i>Donasi </a></li>
    <li class="active">Data Donasi</li>
   </ol>
  </section>

  <section class="content">
   <div class="row">
    <div class="col-xs-12">
     <div class="box">
      <div class="box-header">
       <h3 class="box-title">Tabel Data Donasi</h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
       <table id="example2" class="table table-bordered table-hover">
        <thead>
        <tr>
         <th>No</th>
         <th>Donatur</th>
         <th>Lokasi</th>
         <th>Jenis Barang</th>
         <th>Jumlah</th>
         <th>Keterangan</th>
         {{--<th>Status</th>--}}
         <th>Penjemputan</th>
        </tr>
        </thead>
        <tbody>
        @foreach($datadonasi as $row)
         <tr>
          <td>{{$number}}</td>
          <td>{{$row['name']}}</td>
          <td>{{$row['lokasi']}}</td>
          <td>{{$row['jenis_barang']}}</td>
          <td>{{$row['jumlah']}}</td>
          <td>{{$row['keterangan']}}</td>
          {{--<td>--}}
           {{--<button class="btn btn-warning">Sedang dijemput</button>--}}
          {{--</td>--}}
          <td>
           <a href="{{action('DatadonasiController@edit',$row['id'])}}" class="btn btn-info">Penjemputan</a>
          </td>
          {{--<td>{{$row['donasi']}}</td>--}}

          {{--<td><a href="{{action('DatadonasiController@edit', $row['id'])}}" class="btn btn-warning">Edit</a></td>--}}
          {{--<td>--}}
          {{--<form method="post" class="delete_form" action="{{action('DatadonasiController@destroy', $row['id'])}}">--}}
          {{--{{csrf_field()}}--}}
          {{--<input type="hidden" name="_method" value="DELETE" />--}}
          {{--<button type="submit" class="btn btn-danger">Hapus</button>--}}
          {{--</form>--}}
          {{--</td>--}}
         </tr>
         <?php $number++; ?>
        @endforeach
        </tbody>
       </table>
      </div>
      <!-- /.box-body -->
     </div>
     <!-- /.box -->
    </div>
    <!-- /.col -->
   </div>
   <!-- /.row -->
   <!-- Main row -->
   <div class="row">
    <!-- /.Left col -->
    <!-- right col (We are only adding the ID to make the widgets sortable)-->
    <section class="col-lg-5 connectedSortable">

    </section>
    <!-- right col -->
   </div>
   <!-- /.row (main row) -->
  </section>
  {{--<section class="content-header">--}}
   {{--<div class="row">--}}
    {{--<div class="col-md-12">--}}
     {{--<br />--}}
     {{--<h3 align="center">Data Donasi yang Telah Masuk</h3>--}}
     {{--<br />--}}
     {{--@if($message = Session::get('success'))--}}
      {{--<div class="alert alert-success">--}}
       {{--<p>{{$message}}</p>--}}
      {{--</div>--}}
     {{--@endif--}}
     {{--<div align="right">--}}
      {{--<a href="{{route('databencana.create')}}" class="btn btn-primary">Tambah</a>--}}
      {{--<br />--}}
      {{--<br />--}}
     {{--</div>--}}

     {{--<table class="table table-bordered table-striped">--}}
      {{--<tr>--}}
       {{--<th>Kode Donasi</th>--}}
       {{--<th>Jenis Barang</th>--}}
       {{--<th>Donasi</th>--}}
       {{--<th>Jumlah</th>--}}
       {{--<th>Keterangan</th>--}}
       {{--<th>Lokasi</th>--}}
       {{--<th>Edit</th>--}}
       {{--<th>Hapus</th>--}}
      {{--</tr>--}}
      {{--@foreach($datadonasi as $row)--}}
       {{--<tr>--}}
        {{--<td>{{$row['kode_donasi']}}</td>--}}
        {{--<td>{{$row['jenis_barang']}}</td>--}}
        {{--<td>{{$row['donasi']}}</td>--}}
        {{--<td>{{$row['jumlah']}}</td>--}}
        {{--<td>{{$row['keterangan']}}</td>--}}
        {{--<td>{{$row['lokasi']}}</td>--}}
        {{--<td><a href="{{action('DatadonasiController@edit', $row['id'])}}" class="btn btn-warning">Edit</a></td>--}}
        {{--<td>--}}
        {{--<form method="post" class="delete_form" action="{{action('DatadonasiController@destroy', $row['id'])}}">--}}
        {{--{{csrf_field()}}--}}
        {{--<input type="hidden" name="_method" value="DELETE" />--}}
        {{--<button type="submit" class="btn btn-danger">Hapus</button>--}}
        {{--</form>--}}
        {{--</td>--}}
       {{--</tr>--}}
      {{--@endforeach--}}
     {{--</table>--}}
    {{--</div>--}}
   {{--</div>--}}
   {{--<script>--}}
       {{--$(document).ready(function(){--}}
           {{--$('.delete_form').on('submit', function(){--}}
               {{--if(confirm("Are you sure you want to delete it?"))--}}
               {{--{--}}
                   {{--return true;--}}
               {{--}--}}
               {{--else--}}
               {{--{--}}
                   {{--return false;--}}
               {{--}--}}
           {{--});--}}
       {{--});--}}
   {{--</script>--}}
  {{--</section>--}}
 {{--</div>--}}
 </div>
@endsection